const types = {
    SET_COMPANIES: 'SET_COMPANIES',
    SET_ACTIVE_COMPANY: 'SET_ACTIVE_COMPANY',
    SET_ACTIVE_COMPANY_ID: 'SET_ACTIVE_COMPANY_ID',
    SET_ADD_BUTTON_STATUS: 'SET_ADD_BUTTON_STATUS',
};

export default types;