module.exports = {
    CREATE_USER: "CREATE_USER",
    RESTORE_PASSWORD: "RESTORE_PASSWORD",
    UPDATE_EMAIL: "UPDATE_EMAIL",
    INVITE_TO_COMPANY: "INVITE_TO_COMPANY",
    INVITE_TO_FORM: "INVITE_TO_FORM",
    SHARE_FORM: "SHARE_FORM",
};
