const SEARCH = {
    FORMS: "FORMS",
    FORMS_ARCHIVE: "FORMS_ARCHIVE",
    COMPANY_ALL: "COMPANY_ALL",
    COMPANY_MY: "COMPANY_MY",
    COMPANY_SHARED: "COMPANY_SHARED",
};

export default SEARCH;
